### ISSUE TITLE
Concord 3.5.2 breaks vanilla phase field effect.

### ISSUE THREAD

**Issue by ReverseStateMonad** [Sutopia/Starsector-Concord#1]
With Concord enabled, phase ships no longer reduce your fleet's sensor profile when your transponder is turned off.  The hullmod tooltip still says how much reduction there should be, but no reduction is actually applied.

**Comment by Sutopia** [comment]
Fixed with 3.5.2e

**Comment by ReverseStateMonad** [comment]
It's still happening to me in 3.5.2g:
![noreduction](https://user-images.githubusercontent.com/23009720/159198133-1eada4a3-5643-49b5-b4c4-49e93ee143aa.png)
This is with Concord 3.5.2g as the only active mod; you can see that despite having a Revenant and a Gremlin in the fleet, there is no Phase Field reduction to sensor profile.
